import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Shivam Akshayvat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        {/* <div className="fixed top-2 z-50 right-3 py-2 px-4 rounded-full bg-red-600 text-white">
          Site is going to maintainence
        </div> */}
        {children}
        <ToastContainer
          position="top-center"
          autoClose={2500}
          // hideProgressBar={true}
          newestOnTop
          // pauseOnHover={false}
          theme="light"
        />
      </body>
    </html>
  );
}
