name: Deploy to DigitalOcean VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DO_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy code to server
        run: |
          rsync -avz --exclude='.git' ./ root@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_PATH }}/

      - name: Deploy on server
        run: |
          ssh root@${{ secrets.SERVER_IP }} << EOF
            cd ${{ secrets.DEPLOY_PATH }}
            npm install --production
            NODE_OPTIONS="--max-old-space-size=4096" npm run build
            pm2 restart ${{ secrets.PM2_APP_NAME }}
          EOF
